[build]
  command = "npm run build"
  publish = "dist"

# Proxy: cualquier /api/* va a tu backend de Railway donde esta el back
[[redirects]]
  from = "/api/*"
  to = "https://cockpit-assistant-787-production.up.railway.app/api/:splat"
  status = 200
